#!/bin/sh
target=$(basename $(pwd))
tgzname="Gpremacy-Src-$(date +%Y%m%d).tar.gz"

pushd ..

tar --exclude="Project.planner" --exclude="*.gz" --exclude="Original Graphics" -zcf $tgzname  $target

echo "Tarball created in $(pwd)/$tgzname"

gpg -b --use-agent $tgzname

popd

